id = "becker-zed"
name = "Becker Zed Theme"
version = "0.0.1"
schema_version = 1
authors = ["Ernst Becker <ernst.becker.neto@gmail.com>"]
description = "Ernst Becker's personal theme based on his color palette"
repository = "https://github.com/becker-theme/zed"
